# Generated by Django 4.1 on 2022-09-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_contact_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="photo",
            field=models.ImageField(blank=True, upload_to="photos/%y/%m"),
        ),
    ]
