# Generated by Django 4.1 on 2022-09-19 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_contact_photo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact", old_name="photo", new_name="image",
        ),
    ]
