# Generated by Django 4.1 on 2022-09-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0007_remove_contact_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="image",
            field=models.ImageField(blank=True, upload_to="photos/%y/%m"),
        ),
    ]
